version: "3.8"

services:
  orioledb:
    image: orioledb/orioledb:latest-pg16
    container_name: orioledb
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale=C"
  apacheignite:
    image: apacheignite/ignite
    container_name: apacheignite
    ports:
      - "10800:10800"
  surrealdb:
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
  supabasedb:
    image: supabase/postgres
    ports:
      - 5433:5432
    command: postgres -c config_file=/etc/postgressql/postgressql.conf
    environment:
      POSTGRES_PASSWORD: postgres
  couchbase:
    image: couchbase
    container_name: db
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
    environment:
      - COUCHBASE_ROOT_PASSWORD=admin
  cockroachdb:
    image: cockroachdb/cockroach:v19.2.2
    container_name: cockroachdb
    ports:
      - "26257:26257"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/cockroachdb:/cockroach/cockroach-data"
  hadoop:
    image: sequenceiq/hadoop-docker:2.7.1
    ports:
      - "50070:50070"
  hive4:
    image: apache/hive:4.0.0-beta-1
    ports:
      - "10000:10000"
      - "10002:10002"
    environment:
      SERVICE_NAME: hiveserver2
    depends_on:
      - hadoop
  questdb:
    image: questdb/questdb:7.3.4
    container_name: questdb
    ports:
      - "9000:9000"
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
  kudu-impala:
    image: apache/kudu:impala-latest
    ports:
      - "21000:21000"
      - "21050:21050"
      - "25000:25000"
      - "25010:25010"
      - "25020:25020"
    container_name: impala
